// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define NOTOSERIF_12_FONT_ID (-467754205)
#define NOTOSERIF_14_FONT_ID (1248467164)
#define NOTOSERIF_16_FONT_ID (-1430838797)
#define NOTOSERIF_18_FONT_ID (-1758703393)
#define NOTOSANS_12_FONT_ID (738697906)
#define NOTOSANS_14_FONT_ID (-51545321)
#define NOTOSANS_16_FONT_ID (233583301)
#define NOTOSANS_18_FONT_ID (-905973718)
#define UI_10_FONT_ID (1322569422)
#define UI_12_FONT_ID (1831230762)
#define SMALL_FONT_ID (1465627787)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(NOTOSERIF_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
